### ISSUE TITLE
Answer feedback

### ISSUE THREAD

**Issue by Chris-Tollan** [Declan444/24-7-hackathon-team9#4]
As a user I am told if the answer is correct or incorrect and I receive information about the group the flag is commonly associated with.

- AC1 - The users answer must be checked for correctness.
- AC2 - The user must be informed if their selected answer was correct or not.
- AC3 - The user is also provided with information about the group the flag in each specific question is commonly associated with.

**Comment by JaimieHemmings** [comment]
AC-1 The users answer is checked against the valid answer in the JSON
AC-2 The user recieves immediate feedback on their answer in terms of correctness
AC-3 To a degree, context from the question and answer feedback should give the user clear feedback but specifically identifying the flag and information about it is outside the scope of the current timeframe allowance
